# PATHS 
paths-windows:
  dr: D:\data\DLC_clips  # dr -> directory with videos to use for training and or analysis
  project_path: D:\data\DLC_nets  # project_path -> dlc project working directory (where the project will be stored)

# DLC project NAME
experiment: 'Barnes'
experimenter: 'Philip'

# DLC select videos options
number_of_training_videos: 10  # number of videos to use to generate the training set
video_format: 'avi'

# DLC behaviour
extract_frames_mode: 'kmeans'    # 'uniform' vs 'kmeans'