# PATHS 
# dr -> directory with videos to use for training and or analysis
# project_path -> dlc project working directory (where the project will be stored)
# cfg_path -> path to the configure yaml file
paths-windows: 
  dr: D:\data\DLC_clips
  project_path: D:\data\DLC_nets
  cfg_path: D:\data\DLC_nets\config.yaml
#paths-mac:
#  cfg_path: "/Users/federicoclaudi/Desktop/testgui-Federico-2018-11-12/config.yaml"
#  dr: "/Users/federicoclaudi/Dropbox (UCL - SWC)/Rotation_vte/raw_data/video"
#  project_path: 'Users/federicoclaudi/Desktop'

# DLC project NAME
experiment: 'Barnes'
experimenter: 'Philip'

# DLC select videos options
number_of_training_videos: 2  # prop of videos to use to generate the training set [roughly]
min_num_vids: 2              # min number of videos to be used
video_format: 'avi'

# DLC behaviour
extract_frames_mode: 'kmeans'    # 'uniform' vs 'kmeans'